# Generated by Django 5.0.6 on 2026-03-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='labeldefinition',
            name='unique_label_per_project',
        ),
        migrations.RemoveConstraint(
            model_name='projectmember',
            name='unique_member_per_project',
        ),
        migrations.AlterUniqueTogether(
            name='labeldefinition',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'user_id')},
        ),
    ]
