# Generated by Django 5.0.6 on 2026-03-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_583549_idx',
            old_name='notif_recipient_read_idx',
        ),
    ]
